import React, { FC } from "react";
import CodePreview from "../../code-preview/code-preview";
import Link from "next/link";

const UseClient: FC = () => {
  return (
    <div>
      <Link href="/">back</Link>
      <CodePreview
        imgURL=""
        content={`
    // we want to add cart count to navbar and this task needs to state management and state management is a client component feature
    // so we have to use "use client" in navbar component but best practice for this task is:
    // we create a client component named App.tsx and App codes are:
    
    "use client"

    import Navbar from "./Navbar"

    const App = ({children}) => {
      return (
        <div>
          <div>
            <Navbar />
          </div>
          <main>{children}</main>
        </div>
      )
    }

    export default App

    // every component that was children for App is rendered as client component
    // now in app/layout.tsx:

    import type { Metadata } from 'next'
    import { Inter } from 'next/font/google'
    import './globals.css'

    import App from "@/components/App"
      
    const inter = Inter({ subsets: ['latin'] })
      
    export const metadata: Metadata = {
      title: 'Create Next App',
      description: 'Generated by create next app',
    }
    
    export default function RootLayout({
      children,
    }: {
      children: React.ReactNode
    }) {
      return (
        <html lang="en">
          <body className={'{inter.className} bg-slate-950 text-slate-100'}>
            <App>{children}</App>
          </body>
        </html>
      )
    }

      `}
      />
    </div>
  );
};

export default UseClient;
